### ISSUE TITLE
Boats being placed out of bounds

### ISSUE THREAD

**Issue by dxmbname** [AHS-AooD-2024/Battleship#24]
The battleship game runs, but sometimes places boats out of bounds.
Here's a sample run:

   1 2 3 4 5 6 7 8 9 10
A  * . . . D . . . . *

B  . . . . D . . . . .

C  . . . . * . . . . .

D  . . . . . . . . . .

E  . . . . . . . . . .

F  . . . . . . . . . .

G  . . . . . . . . . .

H  * . . . . . . . . .

I  A . . . . . . . . .

J  A . . . . . . . . *

The Aircraft carrier which is supposed to be 5 segments long has been cut off at the end, making it impossible to finish the game. I'm assuming it's something wrong with checkExtension() and its helper methods.

**Comment by nathanli5722** [comment]
Fixed
