### ISSUE TITLE
Boat Class

### ISSUE THREAD

**Issue by Something-Inconspicuous** [AHS-AooD-2024/Battleship#3]
Implement a boat class which will describe a boat in a Battleship game. It will have the following methods:

 * A constructor that takes 3 arguments:
      * A string that is one of “Aircraft Carrier,” “Battleship,” “Cruiser,” “Destroyer,” or “Submarine.” Note that the first letter of each word is upper case and the remaining letters are lower case.
        * If you know what an `enum` is, use that instead. Otherwise, I'll just do that later.
      * An instance of the Position class where the boat will start.
      * A string that is one of “horizontal” or “vertical” indicating the orientation of the boat. Note that both strings are entirely lower case.
  * A method called getName that returns the name of the type of ship.
  * A method called getAbbreviation that returns a character, a one letter abbreviation (A,B,C,D or S) for the name of the type of ship.
  * A method called size that returns the number of squares the ship takes up (5 for Aircraft Carrier, 4 for Battleship, 3 for Cruiser and Submarine, 2 for Destroyer).
  * A method called onBoat that takes an instance of Position as an argument and returns true if the Position is on the boat and false otherwise.
  * A method called isHit that takes a Position as an argument and returns a boolean, true if the ship has been hit in that place and false otherwise.
  * A method called hit that takes a Position as an argument. If that argument overlaps the ship, it records the fact that the ship has been hit in that position.
  * A method called sunk that returns a Boolean, true if the ship has been hit on all its squares and false otherwise.
  * A method called position that returns an instance of Position, where your boat will start.
  * A method called direction that returns “horizontal” or “vertical,” the direction of the ship.

Your Boat class may have as many private methods as you feel necessary, but no public methods other than the above should be included.

**Comment by Something-Inconspicuous** [comment]
Any of you can do this; I will try to refrain and let y'all get some practice

**Comment by nathanli5722** [comment]
cool :)
