### ISSUE TITLE
Position Class Tests

### ISSUE THREAD

**Issue by Something-Inconspicuous** [AHS-AooD-2024/Battleship#4]
# Testing

Create a `Test` class (in `/src/test/java/aood/battleship/Test.java`) that has a main method and a second static method called `testPosition`. Have this method thoroughly test the `Position` class while the main method will run all tests.

Use the assignment constraints to write this test and output results with expected results.

## Optional:

Throw an `AssertionError` that specifies what tests exactly failed and how if any test fails.

**Comment by kodingcills** [comment]
committed 
![image](https://github.com/user-attachments/assets/d68e9612-246a-46d1-8330-4476ed3f37fd)
lmk if i need to fix anything, or commit it again
